

/*
IGKDEV @ 2008-2016
Project : IGK 
author: C.A.D . BONDJE DOUE
site: http://www.igkdev.be
file: Resources.Designer.cs
THIS FILE IS A PART OF IGK Library FOR DRSSTUDION APPLICATION.
Read license.text
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE.
*/

using IGK.ICore.WinCore;

using IGK.ICore;
using IGK.ICore.Menu;
using IGK.ICore.WinUI;
using IGK.ICore.Drawing2D;
using IGK.ICore.Drawing2D.Menu;
using IGK.ICore.Drawing2D.WinUI;
using IGK.DrSStudio;
using IGK.DrSStudio.Menu;
using IGK.DrSStudio.WinUI;
using IGK.DrSStudio.Drawing2D.Menu;
using IGK.DrSStudio.Drawing2D.WinUI;
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a ?t? g?n?r? par un outil.
//     Version du runtime :4.0.30319.34011
//
//     Les modifications apport?es ? ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est r?g?n?r?.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IGK.DrSStudio.Drawing2D.Properties {
    using System; /// <summary>
    ///   Une classe de ressource fortement typ?e destin?e, entre autres, ? la consultation des cha?nes localis?es.
    /// </summary>
    // Cette classe a ?t? g?n?r?e automatiquement par la classe StronglyTypedResourceBuilder
    // ? l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis r?ex?cutez ResGen
    // avec l'option /str ou r?g?n?rez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilis?e par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IGK.DrSStudio.Drawing2D.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propri?t? CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources ? l'aide de cette classe de ressource fortement typ?e.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localis?e de type System.Byte[].
        /// </summary>
        internal static byte[] img_zoommode_Center {
            get {
                object obj = ResourceManager.GetObject("img_zoommode_Center", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localis?e de type System.Byte[].
        /// </summary>
        internal static byte[] img_zoommode_Normal {
            get {
                object obj = ResourceManager.GetObject("img_zoommode_Normal", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localis?e de type System.Byte[].
        /// </summary>
        internal static byte[] img_zoommode_Stretch {
            get {
                object obj = ResourceManager.GetObject("img_zoommode_Stretch", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localis?e de type System.Byte[].
        /// </summary>
        internal static byte[] img_zoommode_ZoomCenter {
            get {
                object obj = ResourceManager.GetObject("img_zoommode_ZoomCenter", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Recherche une ressource localis?e de type System.Byte[].
        /// </summary>
        internal static byte[] img_zoommode_ZoomNormal {
            get {
                object obj = ResourceManager.GetObject("img_zoommode_ZoomNormal", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
