

/*
IGKDEV @ 2008-2016
Project : IGK 
author: C.A.D . BONDJE DOUE
site: http://www.igkdev.be
file: CoreBrushes.cs
THIS FILE IS A PART OF IGK Library FOR DRSSTUDION APPLICATION.
Read license.text
THIS SOFTWARE IS PROVIDED "AS IS" AND WITHOUT ANY EXPRESS OR
IMPLIED WARRANTIES, INCLUDING, WITHOUT LIMITATION, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE.
*/
﻿using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace IGK.ICore.Drawing2D
{
    /// <summary>
    /// represent a core registrated brush
    /// </summary>
    public class CoreBrushes
    {
        public static CoreBrush Empty;
        public static readonly CoreBrush Transparent;
        public static readonly CoreBrush Black;
        public static readonly CoreBrush Navy;
        public static readonly CoreBrush DarkBlue;
        public static readonly CoreBrush MediumBlue;
        public static readonly CoreBrush Blue;
        public static readonly CoreBrush DarkGreen;
        public static readonly CoreBrush Green;
        public static readonly CoreBrush Teal;
        public static readonly CoreBrush DarkCyan;
        public static readonly CoreBrush DeepSkyBlue;
        public static readonly CoreBrush DarkTurquoise;
        public static readonly CoreBrush MediumSpringGreen;
        public static readonly CoreBrush Lime;
        public static readonly CoreBrush SpringGreen;
        public static readonly CoreBrush Aqua;
        public static readonly CoreBrush Cyan;
        public static readonly CoreBrush MidnightBlue;
        public static readonly CoreBrush DodgerBlue;
        public static readonly CoreBrush LightSeaGreen;
        public static readonly CoreBrush ForestGreen;
        public static readonly CoreBrush SeaGreen;
        public static readonly CoreBrush DarkSlateGrey;
        public static readonly CoreBrush DarkSlateGray;
        public static readonly CoreBrush LimeGreen;
        public static readonly CoreBrush MediumSeaGreen;
        public static readonly CoreBrush Turquoise;
        public static readonly CoreBrush RoyalBlue;
        public static readonly CoreBrush SteelBlue;
        public static readonly CoreBrush DarkSlateBlue;
        public static readonly CoreBrush MediumTurquoise;
        public static readonly CoreBrush Indigo;
        public static readonly CoreBrush DarkOliveGreen;
        public static readonly CoreBrush CadetBlue;
        public static readonly CoreBrush CornflowerBlue;
        public static readonly CoreBrush MediumAquaMarine;
        public static readonly CoreBrush DimGray;
        public static readonly CoreBrush DimGrey;
        public static readonly CoreBrush SlateBlue;
        public static readonly CoreBrush OliveDrab;
        public static readonly CoreBrush SlateGrey;
        public static readonly CoreBrush SlateGray;
        public static readonly CoreBrush LightSlateGray;
        public static readonly CoreBrush LightSlateGrey;
        public static readonly CoreBrush MediumSlateBlue;
        public static readonly CoreBrush LawnGreen;
        public static readonly CoreBrush Chartreuse;
        public static readonly CoreBrush Aquamarine;
        public static readonly CoreBrush Maroon;
        public static readonly CoreBrush Purple;
        public static readonly CoreBrush Olive;
        public static readonly CoreBrush Grey;
        public static readonly CoreBrush Gray;
        public static readonly CoreBrush SkyBlue;
        public static readonly CoreBrush LightSkyBlue;
        public static readonly CoreBrush BlueViolet;
        public static readonly CoreBrush DarkRed;
        public static readonly CoreBrush DarkMagenta;
        public static readonly CoreBrush SaddleBrown;
        public static readonly CoreBrush DarkSeaGreen;
        public static readonly CoreBrush LightGreen;
        public static readonly CoreBrush MediumPurple;
        public static readonly CoreBrush DarkViolet;
        public static readonly CoreBrush PaleGreen;
        public static readonly CoreBrush DarkOrchid;
        public static readonly CoreBrush YellowGreen;
        public static readonly CoreBrush Sienna;
        public static readonly CoreBrush Brown;
        public static readonly CoreBrush DarkGrey;
        public static readonly CoreBrush DarkGray;
        public static readonly CoreBrush LightBlue;
        public static readonly CoreBrush GreenYellow;
        public static readonly CoreBrush PaleTurquoise;
        public static readonly CoreBrush LightSteelBlue;
        public static readonly CoreBrush PowderBlue;
        public static readonly CoreBrush FireBrick;
        public static readonly CoreBrush DarkGoldenRod;
        public static readonly CoreBrush MediumOrchid;
        public static readonly CoreBrush RosyBrown;
        public static readonly CoreBrush DarkKhaki;
        public static readonly CoreBrush Silver;
        public static readonly CoreBrush MediumVioletRed;
        public static readonly CoreBrush IndianRed;
        public static readonly CoreBrush Peru;
        public static readonly CoreBrush Chocolate;
        public static readonly CoreBrush Tan;
        public static readonly CoreBrush LightGrey;
        public static readonly CoreBrush LightGray;
        public static readonly CoreBrush PaleVioletRed;
        public static readonly CoreBrush Thistle;
        public static readonly CoreBrush Orchid;
        public static readonly CoreBrush GoldenRod;
        public static readonly CoreBrush Crimson;
        public static readonly CoreBrush Gainsboro;
        public static readonly CoreBrush Plum;
        public static readonly CoreBrush BurlyWood;
        public static readonly CoreBrush LightCyan;
        public static readonly CoreBrush Lavender;
        public static readonly CoreBrush DarkSalmon;
        public static readonly CoreBrush Violet;
        public static readonly CoreBrush PaleGoldenRod;
        public static readonly CoreBrush LightCoral;
        public static readonly CoreBrush Khaki;
        public static readonly CoreBrush AliceBlue;
        public static readonly CoreBrush HoneyDew;
        public static readonly CoreBrush Azure;
        public static readonly CoreBrush SandyBrown;
        public static readonly CoreBrush Wheat;
        public static readonly CoreBrush Beige;
        public static readonly CoreBrush WhiteSmoke;
        public static readonly CoreBrush MintCream;
        public static readonly CoreBrush GhostWhite;
        public static readonly CoreBrush Salmon;
        public static readonly CoreBrush AntiqueWhite;
        public static readonly CoreBrush Linen;
        public static readonly CoreBrush LightGoldenRodYellow;
        public static readonly CoreBrush OldLace;
        public static readonly CoreBrush Red;
        public static readonly CoreBrush Magenta;
        public static readonly CoreBrush Fuchsia;
        public static readonly CoreBrush DeepPink;
        public static readonly CoreBrush OrangeRed;
        public static readonly CoreBrush Tomato;
        public static readonly CoreBrush HotPink;
        public static readonly CoreBrush Coral;
        public static readonly CoreBrush Darkorange;
        public static readonly CoreBrush LightSalmon;
        public static readonly CoreBrush Orange;
        public static readonly CoreBrush LightPink;
        public static readonly CoreBrush Pink;
        public static readonly CoreBrush Gold;
        public static readonly CoreBrush PeachPuff;
        public static readonly CoreBrush NavajoWhite;
        public static readonly CoreBrush Moccasin;
        public static readonly CoreBrush Bisque;
        public static readonly CoreBrush MistyRose;
        public static readonly CoreBrush BlanchedAlmond;
        public static readonly CoreBrush PapayaWhip;
        public static readonly CoreBrush LavenderBlush;
        public static readonly CoreBrush SeaShell;
        public static readonly CoreBrush Cornsilk;
        public static readonly CoreBrush LemonChiffon;
        public static readonly CoreBrush FloralWhite;
        public static readonly CoreBrush Snow;
        public static readonly CoreBrush Yellow;
        public static readonly CoreBrush LightYellow;
        public static readonly CoreBrush Ivory;
        public static readonly CoreBrush White;

        static CoreBrushes() {
            Empty = new CoreBrush(null);
            Empty.SetSolidColor(Colorf.FromArgb(0, 0, 0, 0));
            Transparent = new CoreBrush(null);
            Transparent.SetSolidColor(Colorf.FromFloat(0.0f, 0f, 0f, 0f));
            Black = new CoreBrush(null);
            Black.SetSolidColor(Colorf.FromFloat(1.0f, 0f, 0f, 0f));
            Navy = new CoreBrush(null);
            Navy.SetSolidColor(Colorf.FromFloat(1.0f, 0f, 0f, 0.5f));
            DarkBlue = new CoreBrush(null);
            DarkBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0f, 0f, 0.55f));
            MediumBlue = new CoreBrush(null);
            MediumBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0f, 0f, 0.8f));
            Blue = new CoreBrush(null);
            Blue.SetSolidColor(Colorf.FromFloat(1.0f, 0f, 0f, 1f));
            DarkGreen = new CoreBrush(null);
            DarkGreen.SetSolidColor(Colorf.FromFloat(1.0f, 0f, 0.39f, 0f));
            Green = new CoreBrush(null);
            Green.SetSolidColor(Colorf.FromFloat(1.0f, 0f, 0.5f, 0f));
            Teal = new CoreBrush(null);
            Teal.SetSolidColor(Colorf.FromFloat(1.0f, 0f, 0.5f, 0.5f));
            DarkCyan = new CoreBrush(null);
            DarkCyan.SetSolidColor(Colorf.FromFloat(1.0f, 0f, 0.55f, 0.55f));
            DeepSkyBlue = new CoreBrush(null);
            DeepSkyBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0f, 0.75f, 1f));
            DarkTurquoise = new CoreBrush(null);
            DarkTurquoise.SetSolidColor(Colorf.FromFloat(1.0f, 0f, 0.81f, 0.82f));
            MediumSpringGreen = new CoreBrush(null);
            MediumSpringGreen.SetSolidColor(Colorf.FromFloat(1.0f, 0f, 0.98f, 0.6f));
            Lime = new CoreBrush(null);
            Lime.SetSolidColor(Colorf.FromFloat(1.0f, 0f, 1f, 0f));
            SpringGreen = new CoreBrush(null);
            SpringGreen.SetSolidColor(Colorf.FromFloat(1.0f, 0f, 1f, 0.5f));
            Aqua = new CoreBrush(null);
            Aqua.SetSolidColor(Colorf.FromFloat(1.0f, 0f, 1f, 1f));
            Cyan = new CoreBrush(null);
            Cyan.SetSolidColor(Colorf.FromFloat(1.0f, 0f, 1f, 1f));
            MidnightBlue = new CoreBrush(null);
            MidnightBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0.1f, 0.1f, 0.44f));
            DodgerBlue = new CoreBrush(null);
            DodgerBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0.12f, 0.56f, 1f));
            LightSeaGreen = new CoreBrush(null);
            LightSeaGreen.SetSolidColor(Colorf.FromFloat(1.0f, 0.13f, 0.7f, 0.67f));
            ForestGreen = new CoreBrush(null);
            ForestGreen.SetSolidColor(Colorf.FromFloat(1.0f, 0.13f, 0.55f, 0.13f));
            SeaGreen = new CoreBrush(null);
            SeaGreen.SetSolidColor(Colorf.FromFloat(1.0f, 0.18f, 0.55f, 0.34f));
            DarkSlateGrey = new CoreBrush(null);
            DarkSlateGrey.SetSolidColor(Colorf.FromFloat(1.0f, 0.18f, 0.31f, 0.31f));
            DarkSlateGray = new CoreBrush(null);
            DarkSlateGray.SetSolidColor(Colorf.FromFloat(1.0f, 0.18f, 0.31f, 0.31f));
            LimeGreen = new CoreBrush(null);
            LimeGreen.SetSolidColor(Colorf.FromFloat(1.0f, 0.2f, 0.8f, 0.2f));
            MediumSeaGreen = new CoreBrush(null);
            MediumSeaGreen.SetSolidColor(Colorf.FromFloat(1.0f, 0.24f, 0.7f, 0.44f));
            Turquoise = new CoreBrush(null);
            Turquoise.SetSolidColor(Colorf.FromFloat(1.0f, 0.25f, 0.88f, 0.82f));
            RoyalBlue = new CoreBrush(null);
            RoyalBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0.25f, 0.41f, 0.88f));
            SteelBlue = new CoreBrush(null);
            SteelBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0.27f, 0.51f, 0.71f));
            DarkSlateBlue = new CoreBrush(null);
            DarkSlateBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0.28f, 0.24f, 0.55f));
            MediumTurquoise = new CoreBrush(null);
            MediumTurquoise.SetSolidColor(Colorf.FromFloat(1.0f, 0.28f, 0.82f, 0.8f));
            Indigo = new CoreBrush(null);
            Indigo.SetSolidColor(Colorf.FromFloat(1.0f, 0.29f, 0f, 0.51f));
            DarkOliveGreen = new CoreBrush(null);
            DarkOliveGreen.SetSolidColor(Colorf.FromFloat(1.0f, 0.33f, 0.42f, 0.18f));
            CadetBlue = new CoreBrush(null);
            CadetBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0.37f, 0.62f, 0.63f));
            CornflowerBlue = new CoreBrush(null);
            CornflowerBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0.39f, 0.58f, 0.93f));
            MediumAquaMarine = new CoreBrush(null);
            MediumAquaMarine.SetSolidColor(Colorf.FromFloat(1.0f, 0.4f, 0.8f, 0.67f));
            DimGray = new CoreBrush(null);
            DimGray.SetSolidColor(Colorf.FromFloat(1.0f, 0.41f, 0.41f, 0.41f));
            DimGrey = new CoreBrush(null);
            DimGrey.SetSolidColor(Colorf.FromFloat(1.0f, 0.41f, 0.41f, 0.41f));
            SlateBlue = new CoreBrush(null);
            SlateBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0.42f, 0.35f, 0.8f));
            OliveDrab = new CoreBrush(null);
            OliveDrab.SetSolidColor(Colorf.FromFloat(1.0f, 0.42f, 0.56f, 0.14f));
            SlateGrey = new CoreBrush(null);
            SlateGrey.SetSolidColor(Colorf.FromFloat(1.0f, 0.44f, 0.5f, 0.56f));
            SlateGray = new CoreBrush(null);
            SlateGray.SetSolidColor(Colorf.FromFloat(1.0f, 0.44f, 0.5f, 0.56f));
            LightSlateGray = new CoreBrush(null);
            LightSlateGray.SetSolidColor(Colorf.FromFloat(1.0f, 0.47f, 0.53f, 0.6f));
            LightSlateGrey = new CoreBrush(null);
            LightSlateGrey.SetSolidColor(Colorf.FromFloat(1.0f, 0.47f, 0.53f, 0.6f));
            MediumSlateBlue = new CoreBrush(null);
            MediumSlateBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0.48f, 0.41f, 0.93f));
            LawnGreen = new CoreBrush(null);
            LawnGreen.SetSolidColor(Colorf.FromFloat(1.0f, 0.49f, 0.99f, 0f));
            Chartreuse = new CoreBrush(null);
            Chartreuse.SetSolidColor(Colorf.FromFloat(1.0f, 0.5f, 1f, 0f));
            Aquamarine = new CoreBrush(null);
            Aquamarine.SetSolidColor(Colorf.FromFloat(1.0f, 0.5f, 1f, 0.83f));
            Maroon = new CoreBrush(null);
            Maroon.SetSolidColor(Colorf.FromFloat(1.0f, 0.5f, 0f, 0f));
            Purple = new CoreBrush(null);
            Purple.SetSolidColor(Colorf.FromFloat(1.0f, 0.5f, 0f, 0.5f));
            Olive = new CoreBrush(null);
            Olive.SetSolidColor(Colorf.FromFloat(1.0f, 0.5f, 0.5f, 0f));
            Grey = new CoreBrush(null);
            Grey.SetSolidColor(Colorf.FromFloat(1.0f, 0.5f, 0.5f, 0.5f));
            Gray = new CoreBrush(null);
            Gray.SetSolidColor(Colorf.FromFloat(1.0f, 0.5f, 0.5f, 0.5f));
            SkyBlue = new CoreBrush(null);
            SkyBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0.53f, 0.81f, 0.92f));
            LightSkyBlue = new CoreBrush(null);
            LightSkyBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0.53f, 0.81f, 0.98f));
            BlueViolet = new CoreBrush(null);
            BlueViolet.SetSolidColor(Colorf.FromFloat(1.0f, 0.54f, 0.17f, 0.89f));
            DarkRed = new CoreBrush(null);
            DarkRed.SetSolidColor(Colorf.FromFloat(1.0f, 0.55f, 0f, 0f));
            DarkMagenta = new CoreBrush(null);
            DarkMagenta.SetSolidColor(Colorf.FromFloat(1.0f, 0.55f, 0f, 0.55f));
            SaddleBrown = new CoreBrush(null);
            SaddleBrown.SetSolidColor(Colorf.FromFloat(1.0f, 0.55f, 0.27f, 0.07f));
            DarkSeaGreen = new CoreBrush(null);
            DarkSeaGreen.SetSolidColor(Colorf.FromFloat(1.0f, 0.56f, 0.74f, 0.56f));
            LightGreen = new CoreBrush(null);
            LightGreen.SetSolidColor(Colorf.FromFloat(1.0f, 0.56f, 0.93f, 0.56f));
            MediumPurple = new CoreBrush(null);
            MediumPurple.SetSolidColor(Colorf.FromFloat(1.0f, 0.58f, 0.44f, 0.85f));
            DarkViolet = new CoreBrush(null);
            DarkViolet.SetSolidColor(Colorf.FromFloat(1.0f, 0.58f, 0f, 0.83f));
            PaleGreen = new CoreBrush(null);
            PaleGreen.SetSolidColor(Colorf.FromFloat(1.0f, 0.6f, 0.98f, 0.6f));
            DarkOrchid = new CoreBrush(null);
            DarkOrchid.SetSolidColor(Colorf.FromFloat(1.0f, 0.6f, 0.2f, 0.8f));
            YellowGreen = new CoreBrush(null);
            YellowGreen.SetSolidColor(Colorf.FromFloat(1.0f, 0.6f, 0.8f, 0.2f));
            Sienna = new CoreBrush(null);
            Sienna.SetSolidColor(Colorf.FromFloat(1.0f, 0.63f, 0.32f, 0.18f));
            Brown = new CoreBrush(null);
            Brown.SetSolidColor(Colorf.FromFloat(1.0f, 0.65f, 0.16f, 0.16f));
            DarkGrey = new CoreBrush(null);
            DarkGrey.SetSolidColor(Colorf.FromFloat(1.0f, 0.66f, 0.66f, 0.66f));
            DarkGray = new CoreBrush(null);
            DarkGray.SetSolidColor(Colorf.FromFloat(1.0f, 0.66f, 0.66f, 0.66f));
            LightBlue = new CoreBrush(null);
            LightBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0.68f, 0.85f, 0.9f));
            GreenYellow = new CoreBrush(null);
            GreenYellow.SetSolidColor(Colorf.FromFloat(1.0f, 0.68f, 1f, 0.18f));
            PaleTurquoise = new CoreBrush(null);
            PaleTurquoise.SetSolidColor(Colorf.FromFloat(1.0f, 0.69f, 0.93f, 0.93f));
            LightSteelBlue = new CoreBrush(null);
            LightSteelBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0.69f, 0.77f, 0.87f));
            PowderBlue = new CoreBrush(null);
            PowderBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0.69f, 0.88f, 0.9f));
            FireBrick = new CoreBrush(null);
            FireBrick.SetSolidColor(Colorf.FromFloat(1.0f, 0.7f, 0.13f, 0.13f));
            DarkGoldenRod = new CoreBrush(null);
            DarkGoldenRod.SetSolidColor(Colorf.FromFloat(1.0f, 0.72f, 0.53f, 0.04f));
            MediumOrchid = new CoreBrush(null);
            MediumOrchid.SetSolidColor(Colorf.FromFloat(1.0f, 0.73f, 0.33f, 0.83f));
            RosyBrown = new CoreBrush(null);
            RosyBrown.SetSolidColor(Colorf.FromFloat(1.0f, 0.74f, 0.56f, 0.56f));
            DarkKhaki = new CoreBrush(null);
            DarkKhaki.SetSolidColor(Colorf.FromFloat(1.0f, 0.74f, 0.72f, 0.42f));
            Silver = new CoreBrush(null);
            Silver.SetSolidColor(Colorf.FromFloat(1.0f, 0.75f, 0.75f, 0.75f));
            MediumVioletRed = new CoreBrush(null);
            MediumVioletRed.SetSolidColor(Colorf.FromFloat(1.0f, 0.78f, 0.08f, 0.52f));
            IndianRed = new CoreBrush(null);
            IndianRed.SetSolidColor(Colorf.FromFloat(1.0f, 0.8f, 0.36f, 0.36f));
            Peru = new CoreBrush(null);
            Peru.SetSolidColor(Colorf.FromFloat(1.0f, 0.8f, 0.52f, 0.25f));
            Chocolate = new CoreBrush(null);
            Chocolate.SetSolidColor(Colorf.FromFloat(1.0f, 0.82f, 0.41f, 0.12f));
            Tan = new CoreBrush(null);
            Tan.SetSolidColor(Colorf.FromFloat(1.0f, 0.82f, 0.71f, 0.55f));
            LightGrey = new CoreBrush(null);
            LightGrey.SetSolidColor(Colorf.FromFloat(1.0f, 0.83f, 0.83f, 0.83f));
            LightGray = new CoreBrush(null);
            LightGray.SetSolidColor(Colorf.FromFloat(1.0f, 0.83f, 0.83f, 0.83f));
            PaleVioletRed = new CoreBrush(null);
            PaleVioletRed.SetSolidColor(Colorf.FromFloat(1.0f, 0.85f, 0.44f, 0.58f));
            Thistle = new CoreBrush(null);
            Thistle.SetSolidColor(Colorf.FromFloat(1.0f, 0.85f, 0.75f, 0.85f));
            Orchid = new CoreBrush(null);
            Orchid.SetSolidColor(Colorf.FromFloat(1.0f, 0.85f, 0.44f, 0.84f));
            GoldenRod = new CoreBrush(null);
            GoldenRod.SetSolidColor(Colorf.FromFloat(1.0f, 0.85f, 0.65f, 0.13f));
            Crimson = new CoreBrush(null);
            Crimson.SetSolidColor(Colorf.FromFloat(1.0f, 0.86f, 0.08f, 0.24f));
            Gainsboro = new CoreBrush(null);
            Gainsboro.SetSolidColor(Colorf.FromFloat(1.0f, 0.86f, 0.86f, 0.86f));
            Plum = new CoreBrush(null);
            Plum.SetSolidColor(Colorf.FromFloat(1.0f, 0.87f, 0.63f, 0.87f));
            BurlyWood = new CoreBrush(null);
            BurlyWood.SetSolidColor(Colorf.FromFloat(1.0f, 0.87f, 0.72f, 0.53f));
            LightCyan = new CoreBrush(null);
            LightCyan.SetSolidColor(Colorf.FromFloat(1.0f, 0.88f, 1f, 1f));
            Lavender = new CoreBrush(null);
            Lavender.SetSolidColor(Colorf.FromFloat(1.0f, 0.9f, 0.9f, 0.98f));
            DarkSalmon = new CoreBrush(null);
            DarkSalmon.SetSolidColor(Colorf.FromFloat(1.0f, 0.91f, 0.59f, 0.48f));
            Violet = new CoreBrush(null);
            Violet.SetSolidColor(Colorf.FromFloat(1.0f, 0.93f, 0.51f, 0.93f));
            PaleGoldenRod = new CoreBrush(null);
            PaleGoldenRod.SetSolidColor(Colorf.FromFloat(1.0f, 0.93f, 0.91f, 0.67f));
            LightCoral = new CoreBrush(null);
            LightCoral.SetSolidColor(Colorf.FromFloat(1.0f, 0.94f, 0.5f, 0.5f));
            Khaki = new CoreBrush(null);
            Khaki.SetSolidColor(Colorf.FromFloat(1.0f, 0.94f, 0.9f, 0.55f));
            AliceBlue = new CoreBrush(null);
            AliceBlue.SetSolidColor(Colorf.FromFloat(1.0f, 0.94f, 0.97f, 1f));
            HoneyDew = new CoreBrush(null);
            HoneyDew.SetSolidColor(Colorf.FromFloat(1.0f, 0.94f, 1f, 0.94f));
            Azure = new CoreBrush(null);
            Azure.SetSolidColor(Colorf.FromFloat(1.0f, 0.94f, 1f, 1f));
            SandyBrown = new CoreBrush(null);
            SandyBrown.SetSolidColor(Colorf.FromFloat(1.0f, 0.96f, 0.64f, 0.38f));
            Wheat = new CoreBrush(null);
            Wheat.SetSolidColor(Colorf.FromFloat(1.0f, 0.96f, 0.87f, 0.7f));
            Beige = new CoreBrush(null);
            Beige.SetSolidColor(Colorf.FromFloat(1.0f, 0.96f, 0.96f, 0.86f));
            WhiteSmoke = new CoreBrush(null);
            WhiteSmoke.SetSolidColor(Colorf.FromFloat(1.0f, 0.96f, 0.96f, 0.96f));
            MintCream = new CoreBrush(null);
            MintCream.SetSolidColor(Colorf.FromFloat(1.0f, 0.96f, 1f, 0.98f));
            GhostWhite = new CoreBrush(null);
            GhostWhite.SetSolidColor(Colorf.FromFloat(1.0f, 0.97f, 0.97f, 1f));
            Salmon = new CoreBrush(null);
            Salmon.SetSolidColor(Colorf.FromFloat(1.0f, 0.98f, 0.5f, 0.45f));
            AntiqueWhite = new CoreBrush(null);
            AntiqueWhite.SetSolidColor(Colorf.FromFloat(1.0f, 0.98f, 0.92f, 0.84f));
            Linen = new CoreBrush(null);
            Linen.SetSolidColor(Colorf.FromFloat(1.0f, 0.98f, 0.94f, 0.9f));
            LightGoldenRodYellow = new CoreBrush(null);
            LightGoldenRodYellow.SetSolidColor(Colorf.FromFloat(1.0f, 0.98f, 0.98f, 0.82f));
            OldLace = new CoreBrush(null);
            OldLace.SetSolidColor(Colorf.FromFloat(1.0f, 0.99f, 0.96f, 0.9f));
            Red = new CoreBrush(null);
            Red.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0f, 0f));
            Magenta = new CoreBrush(null);
            Magenta.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0f, 1f));
            Fuchsia = new CoreBrush(null);
            Fuchsia.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0f, 1f));
            DeepPink = new CoreBrush(null);
            DeepPink.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.08f, 0.58f));
            OrangeRed = new CoreBrush(null);
            OrangeRed.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.27f, 0f));
            Tomato = new CoreBrush(null);
            Tomato.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.39f, 0.28f));
            HotPink = new CoreBrush(null);
            HotPink.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.41f, 0.71f));
            Coral = new CoreBrush(null);
            Coral.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.5f, 0.31f));
            Darkorange = new CoreBrush(null);
            Darkorange.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.55f, 0f));
            LightSalmon = new CoreBrush(null);
            LightSalmon.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.63f, 0.48f));
            Orange = new CoreBrush(null);
            Orange.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.65f, 0f));
            LightPink = new CoreBrush(null);
            LightPink.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.71f, 0.76f));
            Pink = new CoreBrush(null);
            Pink.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.75f, 0.8f));
            Gold = new CoreBrush(null);
            Gold.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.84f, 0f));
            PeachPuff = new CoreBrush(null);
            PeachPuff.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.85f, 0.73f));
            NavajoWhite = new CoreBrush(null);
            NavajoWhite.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.87f, 0.68f));
            Moccasin = new CoreBrush(null);
            Moccasin.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.89f, 0.71f));
            Bisque = new CoreBrush(null);
            Bisque.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.89f, 0.77f));
            MistyRose = new CoreBrush(null);
            MistyRose.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.89f, 0.88f));
            BlanchedAlmond = new CoreBrush(null);
            BlanchedAlmond.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.92f, 0.8f));
            PapayaWhip = new CoreBrush(null);
            PapayaWhip.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.94f, 0.84f));
            LavenderBlush = new CoreBrush(null);
            LavenderBlush.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.94f, 0.96f));
            SeaShell = new CoreBrush(null);
            SeaShell.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.96f, 0.93f));
            Cornsilk = new CoreBrush(null);
            Cornsilk.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.97f, 0.86f));
            LemonChiffon = new CoreBrush(null);
            LemonChiffon.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.98f, 0.8f));
            FloralWhite = new CoreBrush(null);
            FloralWhite.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.98f, 0.94f));
            Snow = new CoreBrush(null);
            Snow.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 0.98f, 0.98f));
            Yellow = new CoreBrush(null);
            Yellow.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 1f, 0f));
            LightYellow = new CoreBrush(null);
            LightYellow.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 1f, 0.88f));
            Ivory = new CoreBrush(null);
            Ivory.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 1f, 0.94f));
            White = new CoreBrush(null);
            White.SetSolidColor(Colorf.FromFloat(1.0f, 1f, 1f, 1f));
        }
    }
}
